BEGIN;

CREATE TABLE public.athletes
(
    athlete_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    full_name VARCHAR(150) NOT NULL,
    date_of_birth DATE,
    sex VARCHAR(20),

    height_cm NUMERIC(5, 2),
    weight_kg NUMERIC(5, 2),

    time_zone_name VARCHAR(100) NOT NULL
        DEFAULT 'Asia/Ho_Chi_Minh',

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_athletes_full_name
        CHECK (btrim(full_name) <> ''),

    CONSTRAINT ck_athletes_height
        CHECK (
            height_cm IS NULL
            OR height_cm BETWEEN 80 AND 250
        ),

    CONSTRAINT ck_athletes_weight
        CHECK (
            weight_kg IS NULL
            OR weight_kg BETWEEN 25 AND 300
        )
);

CREATE TABLE public.app_users
(
    app_user_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    google_subject VARCHAR(255) NOT NULL,
    email_normalized VARCHAR(320) NOT NULL,
    display_name VARCHAR(200),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    last_login_at TIMESTAMPTZ(0),
    onboarding_completed_at TIMESTAMPTZ(0),

    CONSTRAINT uq_app_users_google_subject
        UNIQUE (google_subject),

    CONSTRAINT uq_app_users_email_normalized
        UNIQUE (email_normalized),

    CONSTRAINT ck_app_users_google_subject
        CHECK (btrim(google_subject) <> ''),

    CONSTRAINT ck_app_users_email_normalized
        CHECK (
            email_normalized = lower(btrim(email_normalized))
            AND email_normalized LIKE '%@%'
        )
);

CREATE TABLE public.invitations
(
    invitation_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    email_normalized VARCHAR(320) NOT NULL,

    athlete_id INTEGER,

    access_role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    invited_by_app_user_id INTEGER,

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    expires_at TIMESTAMPTZ(0),
    accepted_at TIMESTAMPTZ(0),

    CONSTRAINT fk_invitations_athletes
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT fk_invitations_invited_by
        FOREIGN KEY (invited_by_app_user_id)
        REFERENCES public.app_users (app_user_id),

    CONSTRAINT ck_invitations_email_normalized
        CHECK (
            email_normalized = lower(btrim(email_normalized))
            AND email_normalized LIKE '%@%'
        ),

    CONSTRAINT ck_invitations_access_role
        CHECK (
            access_role IN ('OWNER', 'COACH', 'RUNNER')
        ),

    CONSTRAINT ck_invitations_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'REVOKED',
                'EXPIRED'
            )
        ),

    CONSTRAINT ck_invitations_athlete_role
        CHECK (
            athlete_id IS NOT NULL
            OR access_role = 'RUNNER'
        ),

    CONSTRAINT ck_invitations_expiry
        CHECK (
            expires_at IS NULL
            OR expires_at > created_at
        ),

    CONSTRAINT ck_invitations_accepted_at
        CHECK (
            status <> 'ACCEPTED'
            OR accepted_at IS NOT NULL
        )
);

CREATE UNIQUE INDEX ux_invitations_pending_target
    ON public.invitations
    (
        email_normalized,
        athlete_id
    )
    NULLS NOT DISTINCT
    WHERE status = 'PENDING';

CREATE TABLE public.athlete_user_access
(
    app_user_id INTEGER NOT NULL,
    athlete_id INTEGER NOT NULL,

    access_role VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    granted_by_app_user_id INTEGER,

    granted_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    revoked_at TIMESTAMPTZ(0),

    CONSTRAINT pk_athlete_user_access
        PRIMARY KEY (app_user_id, athlete_id),

    CONSTRAINT fk_athlete_user_access_user
        FOREIGN KEY (app_user_id)
        REFERENCES public.app_users (app_user_id),

    CONSTRAINT fk_athlete_user_access_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT fk_athlete_user_access_granted_by
        FOREIGN KEY (granted_by_app_user_id)
        REFERENCES public.app_users (app_user_id),

    CONSTRAINT ck_athlete_user_access_role
        CHECK (
            access_role IN ('OWNER', 'COACH', 'RUNNER')
        ),

    CONSTRAINT ck_athlete_user_access_revocation
        CHECK (
            (
                is_active = TRUE
                AND revoked_at IS NULL
            )
            OR
            (
                is_active = FALSE
                AND revoked_at IS NOT NULL
            )
        )
);

CREATE INDEX ix_athlete_user_access_athlete
    ON public.athlete_user_access
    (
        athlete_id,
        app_user_id
    );

CREATE UNIQUE INDEX ux_athlete_user_access_active_runner
    ON public.athlete_user_access (app_user_id)
    WHERE
        access_role = 'RUNNER'
        AND is_active = TRUE;

CREATE TABLE public.athlete_personal_records
(
    personal_record_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,

    distance_m INTEGER NOT NULL,
    completed_duration_sec INTEGER NOT NULL,
    achieved_date DATE NOT NULL,

    record_source VARCHAR(30) NOT NULL
        DEFAULT 'SELF_REPORTED',

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_athlete_personal_records_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT ck_athlete_personal_records_distance
        CHECK (distance_m > 0),

    CONSTRAINT ck_athlete_personal_records_duration
        CHECK (completed_duration_sec > 0)
);

CREATE INDEX ix_athlete_personal_records_latest
    ON public.athlete_personal_records
    (
        athlete_id,
        achieved_date DESC,
        personal_record_id DESC
    );

COMMIT;