BEGIN;

CREATE TABLE public.goals
(
    goal_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,
    goal_name VARCHAR(200) NOT NULL,
    goal_type VARCHAR(30) NOT NULL,

    target_distance_m INTEGER,
    target_duration_sec INTEGER,
    target_date DATE NOT NULL,

    priority_level SMALLINT NOT NULL DEFAULT 3,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_goals_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT ck_goals_type
        CHECK (
            goal_type IN (
                'RACE',
                'DISTANCE',
                'PACE',
                'CONSISTENCY'
            )
        ),

    CONSTRAINT ck_goals_distance
        CHECK (
            target_distance_m IS NULL
            OR target_distance_m > 0
        ),

    CONSTRAINT ck_goals_duration
        CHECK (
            target_duration_sec IS NULL
            OR target_duration_sec > 0
        ),

    CONSTRAINT ck_goals_priority
        CHECK (priority_level BETWEEN 1 AND 5),

    CONSTRAINT ck_goals_status
        CHECK (
            status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')
        )
);

CREATE INDEX ix_goals_athlete_status
    ON public.goals (athlete_id, status);

CREATE TABLE public.training_plans
(
    plan_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,
    goal_id INTEGER NOT NULL,

    plan_name VARCHAR(200) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    planned_days_per_week SMALLINT NOT NULL,
    plan_level VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    version_number INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_training_plans_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT fk_training_plans_goal
        FOREIGN KEY (goal_id)
        REFERENCES public.goals (goal_id),

    CONSTRAINT ck_training_plans_dates
        CHECK (end_date >= start_date),

    CONSTRAINT ck_training_plans_days
        CHECK (planned_days_per_week BETWEEN 1 AND 7),

    CONSTRAINT ck_training_plans_level
        CHECK (
            plan_level IN (
                'BEGINNER',
                'INTERMEDIATE',
                'ADVANCED'
            )
        ),

    CONSTRAINT ck_training_plans_status
        CHECK (
            status IN (
                'DRAFT',
                'ACTIVE',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

CREATE INDEX ix_training_plans_athlete_dates
    ON public.training_plans
    (
        athlete_id,
        start_date,
        end_date
    );

CREATE TABLE public.planned_workouts
(
    planned_workout_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    plan_id INTEGER NOT NULL,
    scheduled_date DATE NOT NULL,

    workout_type VARCHAR(30) NOT NULL,
    workout_name VARCHAR(200) NOT NULL,

    planned_distance_m INTEGER,
    planned_duration_sec INTEGER,
    target_pace_sec_per_km INTEGER,

    target_heart_rate_min SMALLINT,
    target_heart_rate_max SMALLINT,

    priority_weight NUMERIC(4, 2) NOT NULL
        DEFAULT 1.00,

    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    notes VARCHAR(1000),

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_planned_workouts_plan
        FOREIGN KEY (plan_id)
        REFERENCES public.training_plans (plan_id),

    CONSTRAINT uq_planned_workouts_plan_date_name
        UNIQUE (plan_id, scheduled_date, workout_name),

    CONSTRAINT ck_planned_workouts_type
        CHECK (
            workout_type IN (
                'EASY',
                'RECOVERY',
                'LONG_RUN',
                'TEMPO',
                'INTERVAL',
                'RACE',
                'STRENGTH',
                'REST'
            )
        ),

    CONSTRAINT ck_planned_workouts_priority
        CHECK (priority_weight > 0),

    CONSTRAINT ck_planned_workouts_status
        CHECK (
            status IN (
                'PLANNED',
                'COMPLETED',
                'PARTIAL',
                'SKIPPED',
                'RESCHEDULED'
            )
        )
);

CREATE INDEX ix_planned_workouts_plan_date
    ON public.planned_workouts
    (
        plan_id,
        scheduled_date
    );

CREATE TABLE public.completed_activities
(
    activity_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,

    external_source VARCHAR(30) NOT NULL
        DEFAULT 'MANUAL',

    external_activity_id VARCHAR(100),

    activity_date DATE NOT NULL,
    start_time TIMESTAMPTZ(0),

    activity_type VARCHAR(30) NOT NULL DEFAULT 'RUN',

    distance_m INTEGER,
    duration_sec INTEGER,
    moving_time_sec INTEGER,
    average_pace_sec_per_km INTEGER,

    average_heart_rate SMALLINT,
    max_heart_rate SMALLINT,
    elevation_gain_m NUMERIC(8, 2),

    perceived_effort SMALLINT,
    fatigue_score SMALLINT,
    pain_flag BOOLEAN NOT NULL DEFAULT FALSE,

    notes VARCHAR(1000),

    imported_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_completed_activities_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT ck_completed_activities_source
        CHECK (
            external_source IN (
                'STRAVA',
                'GARMIN',
                'EXCEL',
                'MANUAL'
            )
        ),

    CONSTRAINT ck_completed_activities_distance
        CHECK (distance_m IS NULL OR distance_m >= 0),

    CONSTRAINT ck_completed_activities_duration
        CHECK (duration_sec IS NULL OR duration_sec >= 0),

    CONSTRAINT ck_completed_activities_rpe
        CHECK (
            perceived_effort IS NULL
            OR perceived_effort BETWEEN 1 AND 10
        ),

    CONSTRAINT ck_completed_activities_fatigue
        CHECK (
            fatigue_score IS NULL
            OR fatigue_score BETWEEN 1 AND 10
        )
);

CREATE INDEX ix_completed_activities_athlete_date
    ON public.completed_activities
    (
        athlete_id,
        activity_date
    );

CREATE UNIQUE INDEX ux_completed_activities_external
    ON public.completed_activities
    (
        athlete_id,
        external_source,
        external_activity_id
    )
    WHERE external_activity_id IS NOT NULL;

CREATE TABLE public.workout_matches
(
    workout_match_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    planned_workout_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,

    match_method VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    match_confidence NUMERIC(5, 4) NOT NULL DEFAULT 1.0000,

    intensity_completion NUMERIC(5, 4),
    structure_completion NUMERIC(5, 4),

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_workout_matches_workout
        FOREIGN KEY (planned_workout_id)
        REFERENCES public.planned_workouts (planned_workout_id),

    CONSTRAINT fk_workout_matches_activity
        FOREIGN KEY (activity_id)
        REFERENCES public.completed_activities (activity_id),

    CONSTRAINT uq_workout_matches_pair
        UNIQUE (planned_workout_id, activity_id),

    CONSTRAINT uq_workout_matches_activity
        UNIQUE (activity_id),

    CONSTRAINT ck_workout_matches_method
        CHECK (
            match_method IN (
                'MANUAL',
                'DATE',
                'RULE',
                'MODEL'
            )
        ),

    CONSTRAINT ck_workout_matches_confidence
        CHECK (match_confidence BETWEEN 0 AND 1),

    CONSTRAINT ck_workout_matches_intensity
        CHECK (
            intensity_completion IS NULL
            OR intensity_completion BETWEEN 0 AND 1
        ),

    CONSTRAINT ck_workout_matches_structure
        CHECK (
            structure_completion IS NULL
            OR structure_completion BETWEEN 0 AND 1
        )
);

CREATE INDEX ix_workout_matches_planned_workout
    ON public.workout_matches (planned_workout_id);

CREATE TABLE public.daily_wellness
(
    daily_wellness_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,
    wellness_date DATE NOT NULL,

    sleep_hours NUMERIC(4, 2),
    sleep_quality SMALLINT,
    weight_kg NUMERIC(6, 2),

    resting_heart_rate SMALLINT,
    hrv_ms NUMERIC(8, 2),

    fatigue_score NUMERIC(3, 1),
    stress_score NUMERIC(3, 1),
    soreness_score NUMERIC(3, 1),
    energy_score NUMERIC(3, 1),
    mood_score NUMERIC(3, 1),
    motivation_score NUMERIC(3, 1),

    readiness_score NUMERIC(5, 2),
    readiness_band VARCHAR(30),
    data_quality VARCHAR(30),

    notes VARCHAR(1000),

    imported_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_daily_wellness_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT uq_daily_wellness_athlete_date
        UNIQUE (athlete_id, wellness_date),

    CONSTRAINT ck_daily_wellness_fatigue
        CHECK (
            fatigue_score IS NULL
            OR fatigue_score BETWEEN 1 AND 5
        ),

    CONSTRAINT ck_daily_wellness_stress
        CHECK (
            stress_score IS NULL
            OR stress_score BETWEEN 1 AND 5
        ),

    CONSTRAINT ck_daily_wellness_soreness
        CHECK (
            soreness_score IS NULL
            OR soreness_score BETWEEN 1 AND 5
        ),

    CONSTRAINT ck_daily_wellness_readiness
        CHECK (
            readiness_score IS NULL
            OR readiness_score BETWEEN 0 AND 100
        )
);

CREATE TABLE public.strength_sessions
(
    strength_session_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,
    external_session_id VARCHAR(50) NOT NULL,

    session_date DATE NOT NULL,

    planned_exercise_count INTEGER NOT NULL,
    completed_exercise_count INTEGER NOT NULL,

    session_completion_rate NUMERIC(6, 4) NOT NULL,
    completed BOOLEAN NOT NULL,

    imported_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_strength_sessions_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT uq_strength_sessions_external
        UNIQUE (athlete_id, external_session_id),

    CONSTRAINT ck_strength_sessions_counts
        CHECK (
            planned_exercise_count >= 0
            AND completed_exercise_count >= 0
            AND completed_exercise_count <= planned_exercise_count
        ),

    CONSTRAINT ck_strength_sessions_completion
        CHECK (session_completion_rate BETWEEN 0 AND 1)
);

CREATE TABLE public.strength_exercises
(
    strength_exercise_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    strength_session_id BIGINT NOT NULL,
    external_strength_id VARCHAR(100) NOT NULL,

    exercise_name VARCHAR(200) NOT NULL,
    exercise_category VARCHAR(100),

    planned_load_kg NUMERIC(8, 2),
    planned_sets SMALLINT,
    planned_reps_or_duration VARCHAR(100),
    planned_volume_kg NUMERIC(12, 2),
    planned_rpe SMALLINT,

    exercise_side VARCHAR(30),
    coaching_notes VARCHAR(1000),

    exercise_completed BOOLEAN NOT NULL,

    imported_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_strength_exercises_session
        FOREIGN KEY (strength_session_id)
        REFERENCES public.strength_sessions (strength_session_id),

    CONSTRAINT uq_strength_exercises_external
        UNIQUE (
            strength_session_id,
            external_strength_id
        ),

    CONSTRAINT ck_strength_exercises_load
        CHECK (
            planned_load_kg IS NULL
            OR planned_load_kg >= 0
        ),

    CONSTRAINT ck_strength_exercises_sets
        CHECK (
            planned_sets IS NULL
            OR planned_sets > 0
        ),

    CONSTRAINT ck_strength_exercises_volume
        CHECK (
            planned_volume_kg IS NULL
            OR planned_volume_kg >= 0
        ),

    CONSTRAINT ck_strength_exercises_rpe
        CHECK (
            planned_rpe IS NULL
            OR planned_rpe BETWEEN 1 AND 10
        )
);

CREATE INDEX ix_strength_exercises_session
    ON public.strength_exercises
    (
        strength_session_id,
        strength_exercise_id
    );

CREATE TABLE public.mobility_sessions
(
    mobility_session_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    athlete_id INTEGER NOT NULL,
    external_session_id VARCHAR(50) NOT NULL,

    session_date DATE NOT NULL,
    routine VARCHAR(1000),
    completed BOOLEAN NOT NULL,

    imported_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_mobility_sessions_athlete
        FOREIGN KEY (athlete_id)
        REFERENCES public.athletes (athlete_id),

    CONSTRAINT uq_mobility_sessions_external
        UNIQUE (athlete_id, external_session_id)
);

CREATE TABLE public.plan_adjustment_runs
(
    adjustment_run_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    plan_id INTEGER NOT NULL,

    completion_rate NUMERIC(6, 4) NOT NULL,
    threshold_rate NUMERIC(6, 4) NOT NULL,

    window_start_date DATE NOT NULL,
    window_end_date DATE NOT NULL,

    reduction_rate NUMERIC(6, 4) NOT NULL,
    increase_rate NUMERIC(6, 4),

    adjustment_type VARCHAR(20),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    applied_at TIMESTAMPTZ(0),

    CONSTRAINT fk_plan_adjustment_runs_plan
        FOREIGN KEY (plan_id)
        REFERENCES public.training_plans (plan_id),

    CONSTRAINT ck_plan_adjustment_runs_dates
        CHECK (window_end_date >= window_start_date),

    CONSTRAINT ck_plan_adjustment_runs_rates
        CHECK (
            completion_rate BETWEEN 0 AND 1
            AND threshold_rate BETWEEN 0 AND 1
            AND reduction_rate BETWEEN 0 AND 1
            AND (
                increase_rate IS NULL
                OR increase_rate BETWEEN 0 AND 1
            )
        ),

    CONSTRAINT ck_plan_adjustment_runs_type
        CHECK (
            adjustment_type IS NULL
            OR adjustment_type IN (
                'REDUCTION',
                'PROGRESSION'
            )
        ),

    CONSTRAINT ck_plan_adjustment_runs_status
        CHECK (
            status IN (
                'PREVIEW',
                'APPLIED',
                'ROLLED_BACK'
            )
        )
);

CREATE TABLE public.planned_workout_history
(
    planned_workout_history_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    adjustment_run_id BIGINT NOT NULL,
    planned_workout_id BIGINT NOT NULL,
    plan_id INTEGER NOT NULL,

    previous_scheduled_date DATE NOT NULL,
    previous_workout_type VARCHAR(30) NOT NULL,
    previous_workout_name VARCHAR(200) NOT NULL,

    previous_planned_distance_m INTEGER,
    previous_planned_duration_sec INTEGER,
    previous_target_pace_sec_per_km INTEGER,
    previous_target_heart_rate_min SMALLINT,
    previous_target_heart_rate_max SMALLINT,

    previous_priority_weight NUMERIC(4, 2),
    previous_status VARCHAR(20),
    previous_notes VARCHAR(1000),

    new_workout_name VARCHAR(200) NOT NULL,
    new_planned_distance_m INTEGER,
    new_planned_duration_sec INTEGER,
    new_target_pace_sec_per_km INTEGER,
    new_notes VARCHAR(1000),

    changed_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_planned_workout_history_run
        FOREIGN KEY (adjustment_run_id)
        REFERENCES public.plan_adjustment_runs (adjustment_run_id),

    CONSTRAINT fk_planned_workout_history_workout
        FOREIGN KEY (planned_workout_id)
        REFERENCES public.planned_workouts (planned_workout_id),

    CONSTRAINT fk_planned_workout_history_plan
        FOREIGN KEY (plan_id)
        REFERENCES public.training_plans (plan_id)
);

CREATE TABLE public.plan_adjustments
(
    adjustment_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    plan_id INTEGER NOT NULL,
    evaluation_date DATE NOT NULL,

    completion_rate NUMERIC(6, 4) NOT NULL,
    adjustment_type VARCHAR(30) NOT NULL,
    volume_change_percent NUMERIC(6, 2),

    recommendation VARCHAR(1000) NOT NULL,
    reason VARCHAR(1000) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_plan_adjustments_plan
        FOREIGN KEY (plan_id)
        REFERENCES public.training_plans (plan_id),

    CONSTRAINT ck_plan_adjustments_completion
        CHECK (completion_rate BETWEEN 0 AND 1),

    CONSTRAINT ck_plan_adjustments_type
        CHECK (
            adjustment_type IN (
                'KEEP',
                'REDUCE',
                'REPEAT_WEEK',
                'RECOVERY_WEEK',
                'INCREASE',
                'REVIEW'
            )
        ),

    CONSTRAINT ck_plan_adjustments_status
        CHECK (
            status IN (
                'PENDING',
                'ACCEPTED',
                'REJECTED',
                'APPLIED'
            )
        )
);

CREATE TABLE public.activity_reviews
(
    activity_id BIGINT PRIMARY KEY,
    review_status VARCHAR(20) NOT NULL,
    review_reason VARCHAR(500),

    reviewed_at TIMESTAMPTZ(0) NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_activity_reviews_activity
        FOREIGN KEY (activity_id)
        REFERENCES public.completed_activities (activity_id),

    CONSTRAINT ck_activity_reviews_status
        CHECK (
            review_status IN (
                'NEEDS_REVIEW',
                'IGNORED',
                'DUPLICATE',
                'EXTRA'
            )
        )
);

COMMIT;